/// Fix Go files missing package declaration at top
/// يحدث عندما يُنتج LLM Go code بدون "package main" أو "package foo"
pub fn fix_go_missing_package(content: &str, default_pkg: &str) -> String {
    let first_non_empty = content.lines().find(|l| !l.trim().is_empty());
    match first_non_empty {
        Some(line) if line.trim().starts_with("package ") => content.to_string(),
        _ => format!("package {}\n\n{}", default_pkg, content),
    }
}

pub fn fix_rust_string_literals(src: &str) -> String {
    let mut result = String::with_capacity(src.len());
    let bytes = src.as_bytes();
    let mut i = 0;

    while i < bytes.len() {
        if bytes[i] == b'\'' {
            let start = i + 1;
            let mut end = start;
            let mut blocked = false;

            while end < bytes.len() && bytes[end] != b'\'' && bytes[end] != b'\n' {
                if matches!(
                    bytes[end],
                    b' ' | b'\t'
                        | b'('
                        | b')'
                        | b'['
                        | b']'
                        | b'{'
                        | b'}'
                        | b'<'
                        | b'>'
                        | b','
                        | b';'
                        | b':'
                        | b'&'
                ) {
                    blocked = true;
                    break;
                }
                end += 1;
            }

            if !blocked && end < bytes.len() && bytes[end] == b'\'' && end > start {
                let word = &src[start..end];
                let word_len = word.chars().count();

                let is_escape = word.contains('\\');
                let is_char_digit = word_len == 1
                    && word
                        .chars()
                        .next()
                        .map(|c| c.is_ascii_digit())
                        .unwrap_or(false);
                let is_char_single = word_len == 1;

                let should_convert =
                    word_len > 1 && !is_escape && !is_char_digit && !is_char_single;

                if should_convert {
                    result.push('"');
                    result.push_str(word);
                    result.push('"');
                    i = end + 1;
                    continue;
                }
            }
        }

        let Some(ch) = src[i..].chars().next() else {
            break;
        };
        result.push(ch);
        i += ch.len_utf8();
    }

    result
}

/// Sanitize broken Rust lifetime quotes generated by weak LLMs (e.g. Groq).
/// Fixes patterns like `"static str`  `&'static str` and Unicode lifetime markers.
pub fn sanitize_rust_lifetime_quotes(content: &str) -> String {
    content
        // Fix "static  &'static (common Groq hallucination)
        .replace("\"static str", "&'static str")
        .replace("\u{201C}static", "&'static")
        .replace("\u{2018}static", "'static")
        // Fix broken return type arrows
        .replace("-> \"static", "-> &'static")
        .replace("-> \u{201C}static", "-> &'static")
        // Fix missing & before 'static
        .replace("-> 'static str", "-> &'static str")
}

pub fn fix_rust_test_attributes(src: &str) -> String {
    let had_trailing_newline = src.ends_with('\n');
    let mut fixed_lines = Vec::new();

    for line in src.lines() {
        let trimmed = line.trim_start();
        let indent = &line[..line.len() - trimmed.len()];

        if trimmed == "[cfg(test)]" {
            fixed_lines.push(format!("{}#[cfg(test)]", indent));
        } else if trimmed == "[test]" {
            fixed_lines.push(format!("{}#[test]", indent));
        } else {
            fixed_lines.push(line.to_string());
        }
    }

    let mut out = fixed_lines.join("\n");
    if had_trailing_newline {
        out.push('\n');
    }
    out
}

/// v8.0  Fix Llama writing `-go 1.21` instead of `go 1.21` in go.mod files
#[allow(dead_code)] // v9.x: Go module sanitizer — reserved for go.mod repair path
pub fn sanitize_go_mod_content(content: &str) -> String {
    let fixed: Vec<String> = content
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if trimmed.starts_with("-go ") {
                let leading = &line[..line.len() - trimmed.len()];
                format!("{}{}", leading, trimmed.replacen("-go ", "go ", 1))
            } else if trimmed.starts_with("go=") {
                let leading = &line[..line.len() - trimmed.len()];
                format!("{}{}", leading, trimmed.replacen("go=", "go ", 1))
            } else {
                line.to_string()
            }
        })
        .collect();
    let result = fixed.join("\n");
    if result != content {
        eprintln!("    AutoFix: corrected go.mod directive syntax (-go  go)");
    }
    result
}

#[allow(dead_code)] // v9.x: Go module name extractor — reserved for go.mod repair path
pub fn sanitize_go_module_name(cmd: &str) -> String {
    cmd.replace("go mod init main", "go mod init sel_tmp")
}

#[allow(dead_code)] // v9.x: Go module name from stderr — reserved for go.mod autofix
pub fn extract_module_name(stderr: &str) -> Option<String> {
    stderr
        .lines()
        .find(|l| l.contains("ModuleNotFoundError: No module named"))?
        .split('\'')
        .nth(1)
        .map(|s| s.to_string())
}

///    Unicode quotes
pub fn sanitize_code(s: &str) -> String {
    let original_len = s.len();
    let result = s
        .replace(['\u{201C}', '\u{201D}'], "\"")
        .replace(['\u{2018}', '\u{2019}'], "'")
        .replace('\u{2014}', "--")
        .replace('\u{2013}', "-")
        .replace('\u{00A0}', " ")
        .replace(['\u{200B}', '\u{FEFF}'], "")
        .replace("\r\n", "\n")
        .to_string();

    if result.len() != original_len {
        eprintln!(
            "[TRACE] sanitize_code: cleaned {} Unicode chars",
            original_len - result.len()
        );
    }
    result
}

/// Fix Python assert strings where a weak LLM used single quotes outside
/// a payload that already contains tuple/string syntax.
fn normalize_problematic_python_assert(line: &str) -> Option<String> {
    let assert_pos = line.find("assert '")?;
    let quote_start = assert_pos + "assert ".len();
    let after_open = &line[quote_start + 1..];
    let relative_end = after_open.find("' in ")?;
    let quote_end = quote_start + 1 + relative_end;
    let inner = &line[quote_start + 1..quote_end];

    let looks_problematic = inner.contains("('")
        || inner.contains("',")
        || inner.contains("')")
        || inner.contains("[(")
        || inner.contains(")]")
        || inner.contains('"');

    if !looks_problematic {
        return None;
    }

    let normalized_inner = inner.replace('"', "'");
    Some(format!(
        "{}\"{}\"{}",
        &line[..quote_start],
        normalized_inner,
        &line[quote_end + 1..]
    ))
}

pub fn fix_python_string_quoting(src: &str) -> String {
    let had_trailing_newline = src.ends_with('\n');
    let mut fixed_lines = Vec::new();

    for line in src.lines() {
        if let Some(fixed) = normalize_problematic_python_assert(line) {
            fixed_lines.push(fixed);
        } else {
            fixed_lines.push(line.to_string());
        }
    }

    let mut out = fixed_lines.join("\n");
    if had_trailing_newline {
        out.push('\n');
    }
    out
}

#[allow(dead_code)] // documented in SEL_AGENT_REFERENCE_v9.3.2 — Cargo.toml duplicate key fix
pub fn fix_toml_duplicates(src: &str) -> String {
    // v7.5: Basic fix for duplicate keys in [package] section of Cargo.toml
    let lines: Vec<String> = src.lines().map(|s| s.to_string()).collect();
    let mut seen_keys = std::collections::HashSet::new();
    let mut result = Vec::new();

    // We process from bottom to top to keep the LATEST assignment (likely the one the model just added)
    for line in lines.iter().rev() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('[') || trimmed.starts_with('#') {
            result.push(line.clone());
            if trimmed.starts_with('[') {
                seen_keys.clear();
            } // Reset on new section
            continue;
        }

        if let Some(pos) = trimmed.find('=') {
            let key = trimmed[..pos].trim();
            if seen_keys.contains(key) {
                eprintln!(
                    "[TRACE] fix_toml_duplicates: removed duplicate key '{}'",
                    key
                );
                continue;
            }
            seen_keys.insert(key.to_string());
        }
        result.push(line.clone());
    }
    result.reverse();
    result.join("\n")
}

pub fn fix_go_backslashes(src: &str) -> String {
    // v7.5: Fix for illegal backslash escapes in Go strings (common hallucination)
    src.replace("\\\\n", "\\n")
        .replace("\\\\t", "\\t")
        .replace("\\\\\"", "\\\"")
}

pub fn fix_rust_string_types(content: &str) -> String {
    let ends_with_newline = content.ends_with('\n');
    let lines: Vec<String> = content
        .lines()
        .map(|line| {
            let line = fix_rust_pattern(line, "Err(\"", "Err(\"", "\".to_string())");
            let line = fix_rust_pattern(&line, ".ok_or(\"", ".ok_or(\"", "\".to_string())");

            fix_rust_pattern(
                &line,
                ".ok_or_else(|| \"",
                ".ok_or_else(|| \"",
                "\".to_string())",
            )
        })
        .collect();
    let mut out = lines.join("\n");
    if ends_with_newline && !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

///   open + "msg" + )   open + "msg" + new_close
///      .to_string()   msg
pub fn fix_rust_pattern(line: &str, open: &str, new_open: &str, new_close: &str) -> String {
    if !line.contains(open) {
        return line.to_string();
    }
    let mut result = String::new();
    let mut rest = line;
    while let Some(pos) = rest.find(open) {
        result.push_str(&rest[..pos]);
        let after = &rest[pos + open.len()..];
        //     string: "
        if let Some(q) = after.find('"') {
            let msg = &after[..q];
            let tail = &after[q + 1..]; //   "
            if tail.starts_with(".to_string()") {
                //
                result.push_str(new_open);
                result.push_str(msg);
                result.push('"');
                rest = tail; //   .to_string()...
            } else {
                // :  .to_string()  )
                result.push_str(new_open);
                result.push_str(msg);
                result.push_str(new_close);
                //  )
                rest = if let Some(stripped) = tail.strip_prefix(')') {
                    stripped
                } else {
                    tail
                };
            }
        } else {
            //
            result.push_str(open);
            rest = after;
        }
    }
    result.push_str(rest);
    result
}

///  pattern("msg")  pattern("msg".to_string())
// lookahead
#[cfg(test)]
mod tests_rust_autofix {
    use super::*;

    #[test]
    fn test_fix_rust_string_literals_preserves_lifetimes() {
        let input = "pub fn f<'a>(x: &'a str) -> &'a str { x }";
        let got = fix_rust_string_literals(input);
        assert_eq!(got, input);
    }

    #[test]
    fn test_fix_rust_string_literals_converts_single_quoted_strings() {
        let input = "fn main() { let s = 'hello'; }";
        let got = fix_rust_string_literals(input);
        assert!(got.contains("\"hello\""));
    }

    #[test]
    pub fn test_fix_err_str_to_string() {
        let input = r#"fn add(&mut self) -> Result<f64, String> {
    return Err("Not enough values to add");
}
pub fn multiply(&mut self) -> Result<f64, String> {
    return Err("Not enough values to multiply");
}
pub fn pop(&mut self) -> Result<f64, String> {
    self.stack.pop().ok_or("Stack is empty")
}"#;
        let result = fix_rust_string_types(input);
        assert!(result.contains(r#"Err("Not enough values to add".to_string())"#));
        assert!(result.contains(r#"Err("Not enough values to multiply".to_string())"#));
        assert!(result.contains(r#"ok_or("Stack is empty".to_string())"#));
    }

    #[test]
    pub fn test_fix_does_not_double_convert() {
        let input = r#"Err("already fixed".to_string())"#;
        let result = fix_rust_string_types(input);
        assert_eq!(result, r#"Err("already fixed".to_string())"#);
    }

    #[test]
    pub fn test_ok_or_else_fix() {
        let input = r#"self.data.get(0).ok_or_else(|| "No data")"#;
        let result = fix_rust_string_types(input);
        assert!(result.contains(r#"ok_or_else(|| "No data".to_string())"#));
    }
    #[test]
    fn test_fix_python_string_quoting_converts_outer_assert_quotes() {
        let input = r#"assert 'Most common words: [("the", 5)]' in result"#;
        let got = fix_python_string_quoting(input);
        let expected = r#"assert "Most common words: [('the', 5)]" in result"#;
        assert_eq!(got, expected);
    }

    #[test]
    fn test_fix_python_string_quoting_handles_inner_single_quoted_tuples() {
        let input = r#"assert 'Most common words: [('hello', 2), ('world', 2)]' in result"#;
        let got = fix_python_string_quoting(input);
        let expected = r#"assert "Most common words: [('hello', 2), ('world', 2)]" in result"#;
        assert_eq!(got, expected);
    }
}
