// src/executor.rs — v0.4: تنفيذ آمن
use std::collections::HashMap;

use crate::protocol::Cmd;
use crate::types::{ExecResult, SafetyError};
use crate::workspace_oracle::WorkspaceOracle;
use anyhow::{anyhow, Result};
use std::path::PathBuf;
use std::time::{Duration, Instant};
use tokio::process::Command as TCmd;

const ALLOWED: &[&str] = &[
    "python3",
    "python",
    "venv/bin/python3",
    "venv/bin/python",
    "venv/bin/pip3",
    "venv/bin/pip",
    "venv/bin/uvicorn",
    "venv/bin/gunicorn",
    "venv/bin/pytest",
    "pytest",
    "node",
    "npm",
    "npx",
    "node_modules/.bin/jest",
    "cargo",
    "rustc",
    "git",
    "go",
    "mkdir",
    "touch",
    "ls",
    "cat",
    "cp",
    "mv",
    "echo",
    "find",
    "grep",
    "curl",
    "chmod",
    "node",
    "npm",
];

const BLOCKED: &[&str] = &[
    "sudo",
    "rm -rf",
    "mkfs",
    "dd if=",
    "| sh",
    "| bash",
    "curl | bash",
    "> /dev/",
    "/etc/",
    "/sys/",
    "/proc/",
];

pub struct SafeExecutor {
    pub workspace: PathBuf,
    pub oracle: WorkspaceOracle,
    timeout_secs: u64,
    pub replay_mode: bool, // v7.6.1: prevents internet access during replay
    patch_attempts: std::cell::RefCell<HashMap<PathBuf, usize>>, // v5.2: track patch failures
    agent_written_files: std::cell::RefCell<std::collections::HashSet<String>>, // v7.5.1: track agent-created files
}

fn fix_rust_string_literals(src: &str) -> String {
    let mut result = String::with_capacity(src.len());
    let bytes = src.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'\'' {
            let start = i + 1;
            let mut end = start;
            while end < bytes.len() && bytes[end] != b'\'' && bytes[end] != b'\n' {
                end += 1;
            }
            if end < bytes.len() && bytes[end] == b'\'' && end > start {
                let word = &src[start..end];
                let word_len = word.chars().count();

                let is_escape = word.contains('\\');
                let is_lifetime = word
                    .chars()
                    .all(|c| c.is_ascii_lowercase() || c == '_' || c.is_ascii_digit());
                let is_char_digit = word_len == 1
                    && word
                        .chars()
                        .next()
                        .map(|c| c.is_ascii_digit())
                        .unwrap_or(false);
                let is_char_single = word_len == 1;

                let should_convert =
                    word_len > 1 && !is_escape && !is_lifetime && !is_char_digit && !is_char_single;

                if should_convert {
                    result.push('"');
                    result.push_str(word);
                    result.push('"');
                    i = end + 1;
                    continue;
                }
            }
        }
        let ch = src[i..].chars().next().unwrap();
        result.push(ch);
        i += ch.len_utf8();
    }
    result
}

/// Sanitize broken Rust lifetime quotes generated by weak LLMs (e.g. Groq).
/// Fixes patterns like `"static str` → `&'static str` and Unicode lifetime markers.
fn sanitize_rust_lifetime_quotes(content: &str) -> String {
    content
        // Fix "static → &'static (common Groq hallucination)
        .replace("\"static str", "&'static str")
        .replace("\u{201C}static", "&'static")
        .replace("\u{2018}static", "'static")
        // Fix broken return type arrows
        .replace("-> \"static", "-> &'static")
        .replace("-> \u{201C}static", "-> &'static")
        // Fix missing & before 'static
        .replace("-> 'static str", "-> &'static str")
}

impl SafeExecutor {
    pub fn new(workspace: PathBuf, timeout_secs: u64) -> Self {
        let oracle = WorkspaceOracle::new(workspace.clone());
        Self {
            workspace,
            oracle,
            timeout_secs,
            replay_mode: false,
            patch_attempts: std::cell::RefCell::new(HashMap::new()),
            agent_written_files: std::cell::RefCell::new(std::collections::HashSet::new()),
        }
    }

    pub async fn run(&self, cmd: &Cmd) -> Result<ExecResult> {
        match cmd {
            Cmd::Run { command } => self.shell(command).await,
            Cmd::WriteFile { path, content } => self.write_file(path, content),
            Cmd::AppendFile { path, content } => self.append_file(path, content),
            Cmd::DeleteFile { path } => self.delete_file(path),
            Cmd::PatchFile {
                path,
                search,
                replace,
            } => self.patch_file(path, search, replace),
            Cmd::ReadFile { path } => self.read_file(path),
            Cmd::Mkdir { path } => self.mkdir(path),
            Cmd::RunTests { target } => self.run_tests(target).await,
            Cmd::Done { .. } => Ok(ExecResult::ok("done")),
        }
    }

    // ─── Shell ─────────────────────────────────────

    async fn shell(&self, command: &str) -> Result<ExecResult> {
        self.safety_check(command)?;
        let command = sanitize_go_module_name(command);

        let parts: Vec<&str> = command.split_whitespace().collect();
        let prog = parts.first().ok_or_else(|| anyhow!("Empty command"))?;

        // رفض pip install بدون package name
        if prog.contains("pip3") || prog.contains("pip") {
            let is_install = parts.contains(&"install");
            let has_package = parts.len() > 2 && parts.iter().skip(2).any(|p| !p.starts_with('-'));
            if is_install && !has_package {
                return Ok(ExecResult::fail(
                    "pip install needs package name: e.g. venv/bin/pip3 install pytest".to_string(),
                ));
            }
        }

        if !ALLOWED.contains(prog) {
            return Ok(ExecResult::fail(format!(
                "'{}' is not in the allowed programs list",
                prog
            )));
        }

        let services = ["venv/bin/uvicorn", "uvicorn", "venv/bin/gunicorn"];
        if services.contains(prog) {
            return self.service(prog, &parts[1..]).await;
        }

        let start = Instant::now();
        let mut out = tokio::time::timeout(
            Duration::from_secs(self.timeout_secs),
            TCmd::new(prog)
                .args(&parts[1..])
                .current_dir(&self.workspace)
                .env("PYTHONDONTWRITEBYTECODE", "1")
                .output(),
        )
        .await
        .map_err(|_| anyhow!("Timeout after {}s: {}", self.timeout_secs, command))??;

        // --- QuickFix on Run ---
        let out_str = String::from_utf8_lossy(&out.stdout);
        let err_str = String::from_utf8_lossy(&out.stderr);
        let combined = format!("{}\n{}", out_str, err_str);

        if !self.replay_mode && combined.contains("ModuleNotFoundError: No module named") {
            if let Some(module) = extract_module_name(&combined) {
                println!("   ⚡ QuickFix: pip install {}", module);
                let pip = if self.workspace.join("venv/bin/pip3").exists() {
                    "venv/bin/pip3"
                } else {
                    "pip3"
                };
                let _ = TCmd::new(pip)
                    .args(["install", &module])
                    .current_dir(&self.workspace)
                    .output()
                    .await;
                // Re-run
                out = TCmd::new(prog)
                    .args(&parts[1..])
                    .current_dir(&self.workspace)
                    .env("PYTHONDONTWRITEBYTECODE", "1")
                    .output()
                    .await?;
            }
        }

        Ok(ExecResult {
            success: out.status.success(),
            exit_code: out.status.code().unwrap_or(-1),
            stdout: String::from_utf8_lossy(&out.stdout).into(),
            stderr: String::from_utf8_lossy(&out.stderr).into(),
            duration_ms: start.elapsed().as_millis() as u64,
            autofix_triggered: false,
        })
    }

    async fn service(&self, prog: &str, args: &[&str]) -> Result<ExecResult> {
        println!("   🌐 Service: {}", prog);
        TCmd::new(prog)
            .args(args)
            .current_dir(&self.workspace)
            .spawn()?;
        tokio::time::sleep(Duration::from_millis(800)).await;
        Ok(ExecResult::ok("Service started"))
    }

    // ─── File Operations ───────────────────────────

    fn write_file(&self, path: &str, content: &str) -> Result<ExecResult> {
        // v7.5.1: Spec Protection — block overwrite of ONLY pre-existing test/spec files
        // Agent-created test files are allowed to be modified (e.g., to fix missing imports)
        let is_agent_created = self.agent_written_files.borrow().contains(path);
        if self.is_spec_file(path) {
            if self.workspace.join(path).exists() && !is_agent_created {
                return Ok(ExecResult::fail(format!(
                    "SPEC PROTECTION: '{}' already exists — use patch_file to modify existing test/spec files.", path
                )));
            }
        }
        // Track this file as agent-written
        self.agent_written_files
            .borrow_mut()
            .insert(path.to_string());
        {
            let ext = std::path::Path::new(path)
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or("");
            let is_config = matches!(
                path,
                "Cargo.toml"
                    | "go.mod"
                    | "go.sum"
                    | "package.json"
                    | "tsconfig.json"
                    | "Makefile"
                    | ".gitignore"
                    | "README.md"
            );

            if !is_config && !ext.is_empty() {
                if let Err(e) = self.oracle.is_ext_allowed(ext) {
                    return Ok(ExecResult::fail(e));
                }
            }
        }
        let p = self.safe_path(path)?;
        // حماية: ملفات محمية لا يُكتب عليها إذا كانت موجودة (إلا إذا كانت تالفة)
        let protected = ["Cargo.toml", "Cargo.lock", "go.mod", "go.sum"];
        let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");

        let is_valid_protected = if name == "Cargo.toml" && p.exists() {
            std::fs::read_to_string(&p).map(|c| c.contains("[package]")).unwrap_or(false)
        } else if name == "go.mod" && p.exists() {
            // v7.9.1: Allow overwriting newly initialized go.mod (< 100 bytes)
            std::fs::metadata(&p).map(|m| m.len() > 100).unwrap_or(false)
        } else {
            p.exists()
        };

        if protected.contains(&name) && is_valid_protected {
            return Ok(ExecResult::fail(format!(
                "write_file: '{}' is protected — use patch_file to modify existing files",
                path
            )));
        }
        if let Some(parent) = p.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // حماية: إذا كان الملف موجوداً وأكبر بكثير من المحتوى الجديد → تحذير
        if p.exists() {
            let existing_len = std::fs::metadata(&p).map(|m| m.len()).unwrap_or(0);
            let new_len = content.len() as u64;
            if existing_len > 500 && new_len < existing_len / 3 {
                println!(
                    "   ⚠ WARNING: Overwriting {} ({} bytes) with much smaller content ({} bytes)",
                    path, existing_len, new_len
                );
            }
        }
        // Rust brace balance check
        let content = if path.ends_with(".rs") {
            let open = content.chars().filter(|&c| c == '{').count();
            let close = content.chars().filter(|&c| c == '}').count();
            if open > close {
                let mut fixed = content.to_string();
                for _ in 0..(open - close) {
                    fixed.push_str(
                        "
}",
                    );
                }
                std::borrow::Cow::Owned(fixed)
            } else {
                std::borrow::Cow::Borrowed(content)
            }
        } else {
            std::borrow::Cow::Borrowed(content)
        };
        // v5.5: auto-fix single-quote string literals in Rust files
        let content = if p.extension().map(|x| x == "rs").unwrap_or(false) {
            std::borrow::Cow::Owned(fix_rust_string_literals(content.as_ref()))
        } else {
            content
        };
        // v7.5: sanitize Unicode quotes قبل الكتابة
        let mut content_str = sanitize_code(content.as_ref());

        // v7.5: Apply language-specific sanitizers
        if path.ends_with(".go") {
            content_str = fix_go_backslashes(&content_str);
        } else if path.ends_with("go.mod") {
            content_str = sanitize_go_mod_content(&content_str);
        } else if path.ends_with(".toml") {
            content_str = fix_toml_duplicates(&content_str);
        } else if path.ends_with(".rs") {
            content_str = sanitize_rust_lifetime_quotes(&content_str);
            content_str = fix_rust_string_types(&content_str);
        }

        eprintln!(
            "[TRACE] write_file sanitize: input={} output={}",
            content.as_ref().len(),
            content_str.len()
        );
        std::fs::write(&p, content_str.as_bytes())?;
        // Auto-fix: إذا كُتب jest.config.js → احذف "jest" field من package.json
        if path.ends_with("jest.config.js") {
            let pkg = self.workspace.join("package.json");
            if pkg.exists() {
                if let Ok(pkg_src) = std::fs::read_to_string(&pkg) {
                    if let Ok(mut v) = serde_json::from_str::<serde_json::Value>(&pkg_src) {
                        if v.get("jest").is_some() {
                            v.as_object_mut().unwrap().remove("jest");
                            if let Ok(fixed) = serde_json::to_string_pretty(&v) {
                                let _ = std::fs::write(&pkg, fixed);
                                println!("   🔧 AutoFix: removed jest field from package.json (conflicts with jest.config.js)");
                            }
                        }
                    }
                }
            }
        }
        println!("   📝 {} ({} bytes)", path, content.len());
        // v7.5: compile check فوري بعد write_file
        if path.ends_with(".go") {
            // AutoFix: undefined Go stdlib import بدون LLM
            if let Some(err) = go_compile_check(&self.workspace) {
                // حاول AutoFix أولاً
                eprintln!(
                    "[TRACE] Checking autofix for: {}",
                    &err[..std::cmp::min(80, err.len())]
                );
                if let Some(fixed) = autofix_go_undefined_import(&p, &err) {
                    println!("   🔧 AutoFix Go import: {}", fixed);
                    // أعد الفحص بعد الإصلاح
                    if go_compile_check(&self.workspace).is_none() {
                        println!("   ✅ AutoFix succeeded");
                    } else if let Some(err2) = go_compile_check(&self.workspace) {
                        return Ok(ExecResult::fail(format!(
                            "COMPILE ERROR in '{}' — NOTE: The actual error might be in a DIFFERENT file. Check the error details below and fix the file mentioned there:\n{}",
                            path, err2
                        )));
                    }
                } else if let Some(fixed) = autofix_go_unused_import(&p, &err) {
                    println!("   🔧 AutoFix Go unused import: {}", fixed);
                    if let Some(err2) = go_compile_check(&self.workspace) {
                        return Ok(ExecResult::fail(format!(
                            "COMPILE ERROR in '{}' after unused-import autofix:\n{}",
                            path, err2
                        )));
                    }
                    println!("   ✅ AutoFix Go unused import succeeded");
                } else {
                    return Ok(ExecResult::fail(format!(
                        "COMPILE ERROR in '{}' — NOTE: The actual error might be in a DIFFERENT file. Check the error details below and fix the file mentioned there:\n{}",
                        path, err
                    )));
                }
            }
        }
        // v7.9.6: Python syntax check — catches SyntaxError immediately (no LLM needed)
        if path.ends_with(".py") {
            if let Some(err) = python_syntax_check(&p) {
                return Ok(ExecResult::fail(format!(
                    "SYNTAX ERROR in '{}' — fix the Python code:\n{}",
                    path, err
                )));
            }
        }
        Ok(ExecResult::ok(format!("Written: {}", path)))
    }

    fn append_file(&self, path: &str, content: &str) -> Result<ExecResult> {
        let p = self.safe_path(path)?;
        if !p.exists() {
            return Ok(ExecResult::fail(format!(
                "'{}' not found — use write_file first",
                path
            )));
        }
        let mut orig = std::fs::read_to_string(&p)?;
        if !orig.ends_with('\n') {
            orig.push('\n');
        }
        orig.push('\n');
        orig.push_str(content);
        std::fs::write(&p, &orig)?;
        println!("   ➕ {} (+{} bytes)", path, content.len());
        Ok(ExecResult::ok(format!("Appended: {}", path)))
    }

    fn delete_file(&self, path: &str) -> Result<ExecResult> {
        let p = self.safe_path(path)?;
        // حماية: لا نحذف ملفات الإعداد الجذرية
        let protected = ["Cargo.toml", "go.mod", "package.json", "Cargo.lock"];
        let name = p.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if protected.contains(&name) {
            return Ok(ExecResult::fail(format!(
                "delete_file: '{}' is protected and cannot be deleted",
                path
            )));
        }
        // حماية: لا نحذف مجلدات
        if p.is_dir() {
            return Ok(ExecResult::fail(format!(
                "delete_file: '{}' is a directory — only files allowed",
                path
            )));
        }
        if !p.exists() {
            return Ok(ExecResult::ok(format!(
                "delete_file: '{}' already absent",
                path
            )));
        }
        std::fs::remove_file(&p)?;
        println!("   🗑  Deleted: {}", path);
        Ok(ExecResult::ok(format!("Deleted: {}", path)))
    }

    // v5.2: Validate patch result to prevent code corruption
    fn validate_patch(&self, path: &str, original: &str, patched: &str) -> Result<(), String> {
        // 1. Sanity checks for common corruption patterns
        if patched.contains("}ype") || patched.contains("{ype") {
            return Err("Suspicious patch: corrupted type keyword detected".to_string());
        }

        if patched.contains("#\\[") || patched.contains("#\\]") {
            return Err("Invalid Rust escape: backslash in attribute syntax detected".to_string());
        }

        // 2. Line count sanity check
        let orig_lines = original.lines().count();
        let new_lines = patched.lines().count();
        let diff = (new_lines as i32 - orig_lines as i32).abs();

        let max_allowed = (orig_lines * 2).max(50) as i32;
        if diff > max_allowed {
            return Err(format!(
                "Patch changed too many lines: {} → {} lines",
                orig_lines, new_lines
            ));
        }

        // 3. Rust-specific checks
        if path.ends_with(".rs") {
            // Check for unmatched braces (basic)
            let open_braces = patched.matches('{').count();
            let close_braces = patched.matches('}').count();
            if open_braces != close_braces {
                return Err(format!(
                    "Unmatched braces: {} open, {} close",
                    open_braces, close_braces
                ));
            }
        }

        Ok(())
    }

    fn patch_file(&self, path: &str, search: &str, replace: &str) -> Result<ExecResult> {
        // v7.9.9 P6: HARD-BLOCK test file modifications
        if self.is_spec_file(path) {
            let is_agent_created = self.agent_written_files.borrow().contains(path);
            if !is_agent_created {
                // Pre-existing test file — NEVER allow modification
                return Ok(ExecResult::fail(format!(
                    "SPEC PROTECTION: '{}' is a pre-existing test file — NEVER modify test files. Fix the SOURCE code instead.",
                    path
                )));
            }
            // Agent-created test file — we allow modification without strict Assertion Guard
            // because strict guards cause deadlocks if the agent introduces syntax errors
            // and needs to revert its own patches. The mutation engine will catch weak tests anyway.
            eprintln!(
                "[TRACE] SPEC PROTECTION: allowing patch_file on agent-created '{}' (agent's own file)",
                path
            );
        }
        {
            let ext = std::path::Path::new(path)
                .extension()
                .and_then(|e| e.to_str())
                .unwrap_or("");
            let is_config = matches!(
                path,
                "Cargo.toml"
                    | "go.mod"
                    | "go.sum"
                    | "package.json"
                    | "tsconfig.json"
                    | "Makefile"
                    | ".gitignore"
                    | "README.md"
            );

            if !is_config && !ext.is_empty() {
                if let Err(e) = self.oracle.is_ext_allowed(ext) {
                    return Ok(ExecResult::fail(e));
                }
            }
        }
        let p = self.safe_path(path)?;

        // v7.5: CWD Tracking — try subdirectories if direct path fails
        let p = if !p.exists() {
            let resolved = self.resolve_path_with_subdir(path);
            if resolved.exists() {
                resolved
            } else {
                p
            }
        } else {
            p
        };

        // v7.5.3: Pre-flight check for BUG-PATCH-01
        if !p.exists() {
            return Ok(ExecResult::fail(format!(
                "PREFLIGHT_FAIL: '{}' does not exist. Use write_file to create it first, then patch.",
                path
            )));
        }

        // v5.2: Fallback to write_file after 2 failed patch attempts
        {
            let mut attempts = self.patch_attempts.borrow_mut();
            let count = *attempts.entry(p.clone()).or_insert(0);

            if count >= 2 {
                println!(
                    "   ⚠️  patch_file failed {} times on '{}' — switching to write_file fallback",
                    count, path
                );
                drop(attempts); // release borrow

                // Read current content and apply replacement manually
                let content = std::fs::read_to_string(&p)?;
                let content = sanitize_code(&content);
                let search_buf = sanitize_code(search);
                let search = search_buf.as_str();
                let replace_buf = sanitize_code(replace);
                let replace = replace_buf.as_str();
                // FIX(Opus): تحقق من وجود search قبل الكتابة — منع Silent Corruption
                if !content.contains(search) {
                    self.patch_attempts.borrow_mut().insert(p.clone(), 0);
                    return Ok(ExecResult::fail(format!(
                        "PATCH FAILED: search block not found in '{}' after {} attempts — use write_file with complete file content",
                        path, count
                    )));
                }
                let new_content = content.replacen(search, replace, 1);
                let new_content = sanitize_code(&new_content);
                std::fs::write(&p, new_content.as_bytes())?;
                self.patch_attempts.borrow_mut().insert(p.clone(), 0);
                return Ok(ExecResult::ok(format!(
                    "patch_file: fallback write_file applied to '{}' successfully",
                    path
                )));
            }
        }
        if search.trim().is_empty() {
            return Ok(ExecResult::fail(
                "patch_file: search block is empty".to_string(),
            ));
        }
        let content = std::fs::read_to_string(&p)?;
        let content = sanitize_code(&content);
        let search_sanitized = sanitize_code(search);
        let replace_sanitized = sanitize_code(replace);
        let search = search_sanitized.as_str();
        let replace = replace_sanitized.as_str();
        let mut count = content.matches(search).count();
        let mut actual_search = search.to_string();

        // Fallback for Tab vs Space mismatch (common in Go)
        if count == 0 {
            let tabbed_search = search.replace("    ", "\t");
            if content.matches(&tabbed_search).count() > 0 {
                count = content.matches(&tabbed_search).count();
                actual_search = tabbed_search;
            } else {
                let tabbed_search_2 = search.replace("  ", "\t"); // try 2 spaces
                if content.matches(&tabbed_search_2).count() > 0 {
                    count = content.matches(&tabbed_search_2).count();
                    actual_search = tabbed_search_2;
                }
            }
        }

        if count == 0 {
            *self
                .patch_attempts
                .borrow_mut()
                .entry(p.clone())
                .or_insert(0) += 1;
            return Ok(ExecResult::fail(format!(
                "patch_file: search block not found in '{}' — copy the exact text from the file (check tabs/spaces)", path
            )));
        }
        if count > 1 {
            return Ok(ExecResult::fail(format!(
                "patch_file: search block found {} times in '{}' — must be unique, use more context", count, path
            )));
        }
        let new_content = content.replacen(&actual_search, replace, 1);
        if let Err(e) = self.validate_patch(path, &content, &new_content) {
            *self
                .patch_attempts
                .borrow_mut()
                .entry(p.clone())
                .or_insert(0) += 1;
            return Ok(ExecResult::fail(format!(
                "patch_file validation failed: {}",
                e
            )));
        }

        let new_content = if p.extension().map(|x| x == "rs").unwrap_or(false) {
            fix_rust_string_literals(&new_content)
        } else {
            new_content
        };

        // v7.5: Apply language-specific sanitizers post-patch
        let mut final_content = new_content;
        if path.ends_with(".go") {
            final_content = fix_go_backslashes(&final_content);
        } else if path.ends_with(".toml") {
            final_content = fix_toml_duplicates(&final_content);
        }

        std::fs::write(&p, final_content.as_bytes())?;
        self.patch_attempts.borrow_mut().insert(p.clone(), 0);
        println!("   🔧 patch_file: {} (patched)", path);

        if path.ends_with(".go") {
            if let Some(compile_err) = go_compile_check(&self.workspace) {
                eprintln!(
                    "[TRACE] post-patch Go check: {}",
                    &compile_err[..compile_err.len().min(80)]
                );
                if let Some(fixed) = autofix_go_unused_import(&p, &compile_err) {
                    println!("   🔧 AutoFix Go unused import (post-patch): {}", fixed);
                } else if let Some(fixed) = autofix_go_undefined_import(&p, &compile_err) {
                    println!("   🔧 AutoFix Go undefined import (post-patch): {}", fixed);
                }
            }
        }
        // v7.9.6: Python syntax check after patch
        if path.ends_with(".py") {
            if let Some(err) = python_syntax_check(&p) {
                return Ok(ExecResult::fail(format!(
                    "SYNTAX ERROR in '{}' after patch — fix the Python code:\n{}",
                    path, err
                )));
            }
        }

        Ok(ExecResult::ok(format!("Patched: {}", path)))
    }

    fn read_file(&self, path: &str) -> Result<ExecResult> {
        let p = self.safe_path(path)?;
        // v7.5: CWD Tracking — try subdirectories if direct path fails
        let p = if !p.exists() {
            let resolved = self.resolve_path_with_subdir(path);
            if resolved.exists() {
                resolved
            } else {
                p
            }
        } else {
            p
        };
        if !p.exists() {
            return Ok(ExecResult::fail(format!("'{}' not found", path)));
        }
        let content = std::fs::read_to_string(&p)?;
        println!("   📖 {} ({} bytes)", path, content.len());
        Ok(ExecResult {
            success: true,
            exit_code: 0,
            stdout: content,
            stderr: String::new(),
            duration_ms: 0,
            autofix_triggered: false,
        })
    }

    fn mkdir(&self, path: &str) -> Result<ExecResult> {
        std::fs::create_dir_all(self.workspace.join(path))?;
        Ok(ExecResult::ok(format!("mkdir: {}", path)))
    }

    // ─── RunTests ──────────────────────────────────

    async fn run_tests(&self, target: &str) -> Result<ExecResult> {
        let (prog, args) = self.oracle.resolve_test_command(target, self.replay_mode);
        let start = std::time::Instant::now();
        let p_type = self.oracle.current_type();

        println!(
            "   🚀 [Oracle:{:?}] Running: {} {}",
            p_type,
            prog,
            args.join(" ")
        );

        // --- RUST ---
        if prog == "cargo" || prog.ends_with("/cargo") {
            let rust_ws = find_cargo_workspace(&self.workspace);
            let out = tokio::time::timeout(
                std::time::Duration::from_secs(self.timeout_secs),
                TCmd::new("cargo")
                    .args(["test", "--", "--nocapture"])
                    .current_dir(&rust_ws)
                    .output(),
            )
            .await
            .map_err(|_| anyhow!("cargo test timeout"))??;
            let stdout = String::from_utf8_lossy(&out.stdout).to_string();
            let stderr = String::from_utf8_lossy(&out.stderr).to_string();
            let combined = format!("{}\n{}", stdout, stderr);

            // v1.4 Digest AutoFix logic (kept for robustness)
            if combined.contains("trait `Digest` which provides") {
                println!("   🔧 AutoFix: adding sha2::Digest import");
                for dir in [rust_ws.as_path(), rust_ws.join("src").as_path()] {
                    if let Ok(entries) = std::fs::read_dir(dir) {
                        for entry in entries.flatten() {
                            let p = entry.path();
                            if p.extension().and_then(|e| e.to_str()) == Some("rs") {
                                if let Ok(content) = std::fs::read_to_string(&p) {
                                    if content.contains("sha2::Sha256")
                                        && !content.contains("use sha2::Digest")
                                    {
                                        let _ = std::fs::write(
                                            &p,
                                            format!("use sha2::Digest;\n{}", content),
                                        );
                                        println!(
                                            "   ✅ Fixed {:?}",
                                            p.file_name().unwrap_or_default()
                                        );
                                    }
                                }
                            }
                        }
                    }
                }
            }
            let exit_ok = out.status.success();
            let (passed, failed) = parse_rust_tests(&combined);
            let success = exit_ok && passed > 0;
            return Ok(ExecResult {
                success,
                exit_code: out.status.code().unwrap_or(-1),
                stdout: format!("{} passed, {} failed", passed, failed),
                stderr: if success {
                    String::new()
                } else {
                    let s = combined.len().saturating_sub(2000);
                    combined[s..].to_string()
                },
                duration_ms: start.elapsed().as_millis() as u64,
                autofix_triggered: false,
            });
        }

        // --- GO ---
        if prog == "go" || prog.ends_with("/go") {
            let mut autofix_active = false;
            if !self.replay_mode && !self.workspace.join("go.mod").exists() {
                println!("   🔧 AutoFix: go.mod missing — initializing module 'sel_tmp'");
                autofix_active = true;
                let init_out = TCmd::new("go")
                    .args(["mod", "init", "sel_tmp"])
                    .current_dir(&self.workspace)
                    .output()
                    .await;
                match init_out {
                    Ok(o) if o.status.success() => println!("   ✅ go mod init sel_tmp succeeded"),
                    Ok(o) => eprintln!(
                        "   ⚠️ go mod init failed: {}",
                        String::from_utf8_lossy(&o.stderr)
                    ),
                    Err(e) => eprintln!("   ⚠️ go mod init error: {}", e),
                }
            }

            if !self.replay_mode && self.workspace.join("go.mod").exists() {
                let _ = TCmd::new("go")
                    .args(["mod", "tidy"])
                    .current_dir(&self.workspace)
                    .output()
                    .await;
            }

            let out = tokio::time::timeout(
                std::time::Duration::from_secs(self.timeout_secs),
                TCmd::new("go")
                    .args(&args)
                    .current_dir(&self.workspace)
                    .output(),
            )
            .await
            .map_err(|_| anyhow!("go test timeout"))??;

            let combined = format!(
                "{}\n{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            );
            let exit_ok = out.status.success();
            let (passed, failed) = parse_go_tests(&combined);

            let no_test_files = combined.contains("[no test files]");
            let success = (exit_ok && passed > 0) || (exit_ok && no_test_files);

            return Ok(ExecResult {
                success,
                exit_code: out.status.code().unwrap_or(-1),
                stdout: format!("{} passed, {} failed", passed, failed),
                stderr: if success {
                    String::new()
                } else {
                    let s = combined.len().saturating_sub(2000);
                    combined[s..].to_string()
                },
                duration_ms: start.elapsed().as_millis() as u64,
                autofix_triggered: autofix_active,
            });
        }

        // --- NODE / TS ---
        if prog == "npm"
            || prog == "npx"
            || prog == "node"
            || prog.ends_with("/npm")
            || prog.ends_with("/npx")
            || prog.ends_with("/node")
        {
            let mut autofix_active = false;
            let mut out = tokio::time::timeout(
                std::time::Duration::from_secs(self.timeout_secs),
                TCmd::new(&prog)
                    .args(&args)
                    .current_dir(&self.workspace)
                    .output(),
            )
            .await
            .map_err(|_| anyhow!("Node.js test timeout"))??;
            let mut combined = format!(
                "{}\n{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            );

            // AutoFix: Missing Node Module
            if !self.replay_mode && combined.contains("Cannot find module '") {
                if let Some(start) = combined.find("Cannot find module '") {
                    let rest = &combined[start + "Cannot find module '".len()..];
                    if let Some(end) = rest.find('\'') {
                        let module = &rest[..end];
                        if !module.starts_with('.') && !module.starts_with('/') {
                            println!("   ⚡ QuickFix: npm install {}", module);
                            autofix_active = true;
                            let _ = TCmd::new("npm")
                                .args(["install", module])
                                .current_dir(&self.workspace)
                                .output()
                                .await;
                            
                            // Re-run tests after install
                            out = tokio::time::timeout(
                                std::time::Duration::from_secs(self.timeout_secs),
                                TCmd::new(&prog)
                                    .args(&args)
                                    .current_dir(&self.workspace)
                                    .output(),
                            )
                            .await
                            .map_err(|_| anyhow!("Node.js test timeout after AutoFix"))??;
                            
                            combined = format!(
                                "{}\n{}",
                                String::from_utf8_lossy(&out.stdout),
                                String::from_utf8_lossy(&out.stderr)
                            );
                        }
                    }
                }
            }
            let exit_ok = out.status.success();
            let passed = combined
                .lines()
                .filter(|l| l.contains("✓") || l.contains("✔") || l.contains("passed"))
                .count();
            let failed = combined
                .lines()
                .filter(|l| {
                    l.contains("✗") || l.contains("✘") || l.contains("failed") || l.contains("FAIL")
                })
                .count();
            let success = exit_ok && passed > 0;
            return Ok(ExecResult {
                success,
                exit_code: out.status.code().unwrap_or(-1),
                stdout: format!("{} passed, {} failed", passed, failed),
                stderr: if success {
                    String::new()
                } else {
                    let s = combined.len().saturating_sub(2000);
                    combined[s..].to_string()
                },
                duration_ms: start.elapsed().as_millis() as u64,
                autofix_triggered: autofix_active,
            });
        }

        // --- PYTHON ---
        if prog.contains("pytest") || target.contains("pytest") {
            // v7.5.7: Proactive AutoFix for Python venv + pytest
            let mut final_prog = prog.clone();
            let mut autofix_active = false;
            if !self.replay_mode && !self.workspace.join("venv").exists() {
                println!("   🔧 AutoFix: creating venv and installing pytest...");
                autofix_active = true;
                let _ = TCmd::new("python3")
                    .args(["-m", "venv", "venv"])
                    .current_dir(&self.workspace)
                    .output()
                    .await;

                // v7.5.8: Use ABSOLUTE path for venv-specific pip to ensure success on first try
                let pip_bin = self.workspace.join("venv/bin/pip");
                let _ = TCmd::new(pip_bin)
                    .args(["install", "pytest", "--quiet"])
                    .current_dir(&self.workspace)
                    .output()
                    .await;

                // v7.5.1: Update prog to use the new venv
                if self.workspace.join("venv/bin/pytest").exists() {
                    final_prog = "venv/bin/pytest".to_string();
                }
            } else if prog == "pytest" && self.workspace.join("venv/bin/pytest").exists() {
                // v7.5.1: Fallback — if venv exists but model suggested 'pytest'
                final_prog = "venv/bin/pytest".to_string();
            }

            let out = tokio::time::timeout(
                std::time::Duration::from_secs(self.timeout_secs),
                TCmd::new(&final_prog)
                    .args(&args)
                    .current_dir(&self.workspace)
                    .env("PYTHONPATH", &self.workspace)
                    .env("PYTHONDONTWRITEBYTECODE", "1")
                    .output(),
            )
            .await
            .map_err(|_| anyhow!("pytest timeout"))??;
            let combined = format!(
                "{}\n{}",
                String::from_utf8_lossy(&out.stdout),
                String::from_utf8_lossy(&out.stderr)
            );
            let (passed, failed) = parse_pytest(&combined);
            let has_error =
                combined.contains("ERROR collecting") || combined.contains("no tests ran");
            let success = passed > 0 && failed == 0 && !has_error;
            return Ok(ExecResult {
                success,
                exit_code: out.status.code().unwrap_or(-1),
                stdout: format!("{} passed, {} failed", passed, failed),
                stderr: if success {
                    String::new()
                } else {
                    let s = combined.len().saturating_sub(2000);
                    combined[s..].to_string()
                },
                duration_ms: start.elapsed().as_millis() as u64,
                autofix_triggered: autofix_active,
            });
        }

        Ok(ExecResult {
            success: false,
            exit_code: 1,
            stdout: String::new(),
            stderr: format!("No test handler for program: {}", prog),
            duration_ms: start.elapsed().as_millis() as u64,
            autofix_triggered: false,
        })
    }

    // ─── Helpers ───────────────────────────────────

    fn safe_path(&self, path: &str) -> Result<PathBuf> {
        if path.contains("..") {
            return Err(anyhow!(
                SafetyError::PathTraversal(path.to_string()).to_string()
            ));
        }
        let full = self.workspace.join(path);
        if !full.starts_with(&self.workspace) {
            return Err(anyhow!(
                SafetyError::WorkspaceEscape(path.to_string()).to_string()
            ));
        }
        Ok(full)
    }

    fn safety_check(&self, cmd: &str) -> Result<()> {
        let lower = cmd.to_lowercase();
        for b in BLOCKED {
            if lower.contains(b) {
                return Err(anyhow!(
                    SafetyError::BlockedCommand(b.to_string()).to_string()
                ));
            }
        }
        Ok(())
    }

    /// v7.5: CWD Tracking — resolve files in subdirectories when direct path fails
    fn resolve_path_with_subdir(&self, path: &str) -> PathBuf {
        let direct = self.workspace.join(path);
        if direct.exists() {
            return direct;
        }
        // Search in subdirectories (depth 1)
        if let Ok(entries) = std::fs::read_dir(&self.workspace) {
            for entry in entries.flatten() {
                let sub = entry.path();
                if sub.is_dir() {
                    let candidate = sub.join(path);
                    if candidate.exists() {
                        eprintln!(
                            "[TRACE] CWD-FIX: found '{}' in subdir '{}'",
                            path,
                            sub.file_name().unwrap_or_default().to_string_lossy()
                        );
                        return candidate;
                    }
                }
            }
        }
        direct // fallback
    }

    /// v7.5: Spec Protection — checks filename patterns to detect test/spec files
    fn is_spec_file(&self, path: &str) -> bool {
        let filename = std::path::Path::new(path)
            .file_name()
            .and_then(|f| f.to_str())
            .unwrap_or("")
            .to_lowercase();

        filename.starts_with("test_")           // test_main.py
            || filename.ends_with("_test.go")   // main_test.go
            || filename.ends_with("_test.rs")   // main_test.rs
            || filename.contains(".test.")      // app.test.ts
            || filename.contains(".spec.")      // app.spec.ts
            || filename.ends_with("_spec.rb") // main_spec.rb
    }
}

fn parse_pytest(output: &str) -> (usize, usize) {
    let mut passed = 0;
    let mut failed = 0;
    for line in output.lines().rev() {
        if line.contains(" passed") || line.contains(" failed") {
            // السطر: "=== 2 passed, 1 failed in 0.03s ==="
            // نبحث عن الرقم قبل كل كلمة مفتاحية
            for seg in line.split(',') {
                let s = seg.trim();
                let words: Vec<&str> = s.split_whitespace().collect();
                for (i, w) in words.iter().enumerate() {
                    if *w == "passed" && i > 0 {
                        if let Ok(n) = words[i - 1].parse::<usize>() {
                            passed = n;
                        }
                    }
                    if *w == "failed" && i > 0 {
                        if let Ok(n) = words[i - 1].parse::<usize>() {
                            failed = n;
                        }
                    }
                }
            }
            break;
        }
    }
    (passed, failed)
}

#[derive(Debug, PartialEq)]
pub enum MutationResult {
    Strong,
    Weak(String, String), // (original_line, mutated_line)
    Skipped(String),      // Reason
}

fn apply_all_mutations(code: &str) -> Vec<(String, String, String)> {
    let strategies: &[(&str, &str)] = &[
        // ─── Operators (existing) ───
        ("==", "!="),
        ("!=", "=="),
        (" > ", " < "),
        (" < ", " > "),
        (" >= ", " <= "),
        (" <= ", " >= "),
        (" + ", " - "),
        (" - ", " + "),
        // ─── Boolean returns ───
        ("return True", "return False"),
        ("return False", "return True"),
        ("return true", "return false"),       // Go/Rust/TS
        ("return false", "return true"),       // Go/Rust/TS
        // ─── Constants (covers helper.py: return 42) ───
        ("return 0\n", "return 1\n"),
        ("return 1\n", "return 0\n"),
        ("return 42", "return 0"),
        ("return -1", "return 0"),
        // ─── Function swaps (covers max_of_three.py, min/max confusion) ───
        ("max(", "min("),
        ("min(", "max("),
        // ─── Multiplication (covers double.py: x*2) ───
        (" * 2", " * 3"),
        (" * 3", " * 2"),
        (" * ", " / "),
        // ─── Python slice reversal (covers reverse_string.py) ───
        ("[::-1]", "[::1]"),
        // ─── List methods (covers stack.py pop/append) ───
        (".append(", ".insert(0, "),
        // ─── Go/Rust: without-space arithmetic (covers go add: a+b) ───
        ("a+b", "a-b"),
        ("a-b", "a+b"),
        ("a + b", "a - b"),
        ("a - b", "a + b"),
        // ─── Logical operators (Go/TS/Rust) ───
        (" && ", " || "),
        (" || ", " && "),
        // ─── String operations (covers greet.py: f'Hi {name}') ───
        ("f'Hi {", "f'Bye {"),
        ("f\"Hi {", "f\"Bye {"),
        // ─── Modulo (covers is_even: n%2==0) — handled by == already ───
        // ─── Recursion (covers factorial: n-1) ───
        ("n - 1)", "n + 1)"),
        ("n - 1,", "n + 1,"),
    ];

    // أنماط يجب تجاهلها (loop variables وما شابه)
    let skip_patterns = [
        "i += ", "i -= ", "j += ", "j -= ",
        "idx", "index",
        "count +=", "count -=",
        "test", "Test", "assert", "expect",  // لا نطفّر خطوط الاختبار
        "#[", "//",  // Rust attributes and comments
    ];

    let mut result = Vec::new();
    for (from, to) in strategies {
        let mut found_line = None;
        let mutated: String = code
            .lines()
            .map(|line| {
                let trimmed = line.trim_start();
                let skip = trimmed.starts_with('#')
                    || trimmed.starts_with("//")
                    || trimmed.starts_with('*')
                    || trimmed.starts_with("/*")
                    || trimmed.starts_with("import ")
                    || trimmed.starts_with("use ")
                    || skip_patterns.iter().any(|p| line.contains(p));
                if found_line.is_none() && !skip && line.contains(*from) {
                    let new_line = line.replacen(from, to, 1);
                    found_line = Some((line.trim().to_string(), new_line.trim().to_string()));
                    new_line
                } else {
                    line.to_string()
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        if let Some((orig, mutd)) = found_line {
            result.push((mutated, orig, mutd));
        }
    }
    result
}

impl SafeExecutor {
    pub async fn mutation_check(&self, source_file: &str) -> MutationResult {
        let source_path = self.workspace.join(source_file);
        if !source_path.exists() {
            return MutationResult::Skipped("Path not found".into());
        }
        let ext = source_path
            .extension()
            .and_then(|e| e.to_str())
            .unwrap_or("");
        let original = match std::fs::read_to_string(&source_path) {
            Ok(s) => s,
            Err(_) => return MutationResult::Skipped("Read failure".into()),
        };
        let mutations = apply_all_mutations(&original);
        if mutations.is_empty() {
            return MutationResult::Skipped("No mutable patterns found".into());
        }
        // test runner per language
        let test_cmd: Vec<String> = match ext {
            "py" => {
                let pytest = if self.workspace.join("venv/bin/pytest").exists() {
                    "venv/bin/pytest"
                } else {
                    "pytest"
                };
                vec![
                    pytest.into(),
                    "-x".into(),
                    "-q".into(),
                    "--tb=no".into(),
                    "-p".into(),
                    "no:cacheprovider".into(),
                ]
            }
            "go" => vec![
                "go".into(),
                "test".into(),
                "./...".into(),
                "-count=1".into(),
            ],
            "js" | "ts" => {
                let npx = if self.workspace.join("node_modules/.bin/jest").exists() {
                    "node_modules/.bin/jest"
                } else {
                    "npx"
                };
                vec![
                    npx.into(),
                    "--forceExit".into(),
                    "--silent".into(),
                    "--no-cache".into(),
                ]
            }
            "rs" => vec!["cargo".into(), "test".into(), "--quiet".into()],
            _ => return MutationResult::Skipped("Unsupported lang for mutation".into()),
        };
        let mut survived_orig = String::new();
        let mut survived_mutd = String::new();
        let mut any_caught = false;
        let mut any_missed = false;
        for (mutation, orig_line, mutd_line) in &mutations {
            if std::fs::write(&source_path, mutation).is_err() {
                let _ = std::fs::write(&source_path, &original);
                continue;
            }
            // v7.5.3: Safety Buffer — wait for OS file sync/cache invalidation
            std::thread::sleep(std::time::Duration::from_millis(50));
            let out = tokio::time::timeout(
                std::time::Duration::from_secs(30),
                tokio::process::Command::new(&test_cmd[0])
                    .args(&test_cmd[1..])
                    .current_dir(&self.workspace)
                    .env("PYTHONPATH", &self.workspace)
                    .env("PYTHONDONTWRITEBYTECODE", "1")
                    .output(),
            )
            .await;
            let _ = std::fs::write(&source_path, &original);
            if let Ok(Ok(result)) = out {
                if result.status.success() {
                    if !any_missed {
                        survived_orig = orig_line.clone();
                        survived_mutd = mutd_line.clone();
                    }
                    any_missed = true;
                } else {
                    any_caught = true;
                }
            }
            if any_missed {
                break;
            }
        }
        let _ = std::fs::write(&source_path, &original);
        if any_missed {
            MutationResult::Weak(survived_orig, survived_mutd)
        } else if any_caught {
            MutationResult::Strong
        } else {
            MutationResult::Skipped("No survivors".into())
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn ex(dir: &std::path::Path) -> SafeExecutor {
        SafeExecutor::new(dir.to_path_buf(), 10)
    }

    #[test]
    fn write_and_read() {
        let d = tempdir().unwrap();
        let e = ex(d.path());
        e.write_file("a.py", "x=1").unwrap();
        let r = e.read_file("a.py").unwrap();
        assert_eq!(r.stdout, "x=1");
    }

    #[test]
    fn append_file() {
        let d = tempdir().unwrap();
        std::fs::write(d.path().join("a.py"), "line1\n").unwrap();
        let e = ex(d.path());
        let r = e.append_file("a.py", "line2").unwrap();
        assert!(r.success);
        let c = std::fs::read_to_string(d.path().join("a.py")).unwrap();
        assert!(c.contains("line1") && c.contains("line2"));
    }

    #[test]
    fn blocks_path_traversal() {
        let d = tempdir().unwrap();
        let e = ex(d.path());
        assert!(e.write_file("../../etc/passwd", "x").is_err());
    }

    #[tokio::test]
    async fn runs_echo() {
        let d = tempdir().unwrap();
        let e = ex(d.path());
        let r = e
            .run(&Cmd::Run {
                command: "echo hello".into(),
            })
            .await
            .unwrap();
        assert!(r.success);
        assert!(r.stdout.contains("hello"));
    }
}

fn parse_rust_tests(output: &str) -> (usize, usize) {
    let mut total_passed = 0usize;
    let mut total_failed = 0usize;
    for line in output.lines() {
        if line.contains("test result:") {
            for seg in line.split(';') {
                let s = seg.trim();
                let words: Vec<&str> = s.split_whitespace().collect();
                for (i, w) in words.iter().enumerate() {
                    if *w == "passed" && i > 0 {
                        if let Ok(n) = words[i - 1].parse::<usize>() {
                            total_passed += n;
                        }
                    }
                    if *w == "failed" && i > 0 {
                        if let Ok(n) = words[i - 1].parse::<usize>() {
                            total_failed += n;
                        }
                    }
                }
            }
        }
    }
    (total_passed, total_failed)
}

fn parse_go_tests(output: &str) -> (usize, usize) {
    let mut passed = 0usize;
    let mut failed = 0usize;
    for line in output.lines() {
        if line.starts_with("--- PASS") {
            passed += 1;
        }
        if line.starts_with("--- FAIL") {
            failed += 1;
        }
    }
    (passed, failed)
}

fn go_compile_check(workspace: &std::path::Path) -> Option<String> {
    if !workspace.join("go.mod").exists() {
        eprintln!("[TRACE] go_compile_check: skipped (no go.mod)");
        return None;
    }
    eprintln!("[TRACE] go_compile_check: running...");
    let out = std::process::Command::new("go")
        .args(["test", "-run=^$", "-count=1"])
        .current_dir(workspace)
        .output()
        .ok()?;
    if !out.status.success() {
        Some(String::from_utf8_lossy(&out.stderr).to_string())
    } else {
        None
    }
}

/// v7.9.6: Python syntax check — catches SyntaxError/IndentationError without LLM
/// Uses py_compile (stdlib) — works fully offline
fn python_syntax_check(file: &std::path::Path) -> Option<String> {
    if !file.exists() || !file.extension().map(|e| e == "py").unwrap_or(false) {
        return None;
    }
    let file_str = file.to_string_lossy();
    eprintln!("[TRACE] python_syntax_check: checking {}", file_str);
    
    // Use python3 -m py_compile which is stdlib (no pip needed)
    let out = std::process::Command::new("python3")
        .args(["-m", "py_compile", &file_str])
        .output()
        .ok()?;
    
    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr).to_string();
        // Filter to show only the relevant error lines
        let error_msg: String = stderr
            .lines()
            .filter(|l| {
                l.contains("SyntaxError")
                    || l.contains("IndentationError")
                    || l.contains("TabError")
                    || l.contains("File \"")
                    || l.trim().starts_with('^')
                    || l.contains("line ")
            })
            .collect::<Vec<_>>()
            .join("\n");
        if error_msg.is_empty() {
            Some(stderr)
        } else {
            Some(error_msg)
        }
    } else {
        None
    }
}

/// v7.9.9 P6: Semantic Guard for tests
fn guard_assertion_integrity(path: &str, before: &str, after: &str) -> std::result::Result<(), String> {
    let before_asserts = count_assertions(before);
    let after_asserts = count_assertions(after);
    
    if after_asserts < before_asserts {
        return Err(format!(
            "BLOCKED: ASSERTION GUARD: patch on '{}' would reduce assertion count from {} to {} — this weakens test quality. Fix the SOURCE code instead.",
            path, before_asserts, after_asserts
        ));
    }
    
    let before_vals = extract_expected_values(before);
    let after_vals = extract_expected_values(after);
    if !before_vals.is_subset(&after_vals) {
        return Err(format!(
            "BLOCKED: ASSERTION GUARD: patch on '{}' would change expected values (e.g. literals in assertions). This is FORBIDDEN. Fix the SOURCE code to match existing tests.",
            path
        ));
    }
    
    Ok(())
}

/// v7.9.9 P6: Count assertion statements in test file
/// Used by Semantic Guard to prevent test weakening
fn count_assertions(content: &str) -> usize {
    content.lines().filter(|l| {
        let t = l.trim();
        // Python
        t.starts_with("assert ") || t.contains("assertEqual") || t.contains("assertRaises")
        // Go
        || t.contains("t.Errorf") || t.contains("t.Fatal") || t.contains("t.Error(")
        // JS/TS
        || t.contains("expect(") || t.contains("assert.") || t.contains("toBe(")
        // Rust
        || t.contains("assert_eq!") || t.contains("assert_ne!") || t.contains("assert!(")
    }).count()
}

/// v7.9.9 P6: Extract expected values from assertion strings
/// Regex-based heuristic to detect literal changes in tests
fn extract_expected_values(content: &str) -> std::collections::BTreeSet<String> {
    let mut values = std::collections::BTreeSet::new();
    // Extract all numbers and quoted strings as a heuristic for test literals
    let re = regex::Regex::new(r#""[^"]*"|'[^']*'|-?\b\d+\b"#).unwrap();
    for cap in re.captures_iter(content) {
        values.insert(cap[0].to_string());
    }
    values
}

/// AutoFix: يضيف Go stdlib import تلقائياً بدون LLM
fn autofix_go_undefined_import(file: &std::path::Path, err: &str) -> Option<String> {
    let filename = file.file_name()?.to_str()?;
    let go_std: &[(&str, &str)] = &[
        ("fmt", "fmt"),
        ("errors", "errors"),
        ("strings", "strings"),
        ("strconv", "strconv"),
        ("sort", "sort"),
        ("math", "math"),
        ("os", "os"),
        ("io", "io"),
        ("log", "log"),
        ("time", "time"),
        ("sync", "sync"),
        ("context", "context"),
        ("bytes", "bytes"),
        ("bufio", "bufio"),
    ];

    // استخرج الرمز من "undefined: fmt"
    let sym = err
        .lines()
        .find(|l| l.contains(filename) && l.contains("undefined:"))?
        .split("undefined:")
        .nth(1)?
        .split_whitespace()
        .next()?
        .split('.')
        .next()?
        .to_string();

    // تحقق أنه stdlib
    let pkg = go_std
        .iter()
        .find(|(name, _)| *name == sym.as_str())
        .map(|(_, pkg)| *pkg)?;

    // اقرأ الملف
    let src = std::fs::read_to_string(file).ok()?;

    // إذا كان موجوداً بالفعل
    if src.contains(&format!("\"{}\"", pkg)) {
        return None;
    }

    // أضف import
    let new_src = if src.contains("import (") {
        src.replacen("import (", &format!("import (\n\t\"{}\"", pkg), 1)
    } else {
        // أضف بعد package declaration
        let pkg_line = src.lines().find(|l| l.starts_with("package "))?.to_string();
        src.replacen(&pkg_line, &format!("{}\n\nimport \"{}\"", pkg_line, pkg), 1)
    };

    std::fs::write(file, &new_src).ok()?;
    Some(pkg.to_string())
}

/// AutoFix: يحذف Go import غير مستخدم
fn autofix_go_unused_import(file: &std::path::Path, err: &str) -> Option<String> {
    let filename = file.file_name()?.to_str()?;
    let pkg = err
        .lines()
        .find(|l| l.contains(filename) && l.contains("imported and not used"))?
        .split('"')
        .nth(1)?
        .to_string();

    if pkg.is_empty() {
        return None;
    }

    let src = std::fs::read_to_string(file).ok()?;

    let block_pattern = format!("\t\"{}\"", pkg);
    let block_pattern_no_tab = format!("    \"{}\"", pkg);

    let new_src = if src.contains(&block_pattern) {
        let lines: Vec<&str> = src.lines().collect();
        let filtered: Vec<&str> = lines
            .iter()
            .filter(|&&line| {
                let trimmed = line.trim();
                trimmed != format!("\"{}\"", pkg).as_str()
            })
            .cloned()
            .collect();
        let new = filtered.join("\n");
        new.replace("import (\n)", "").replace("import (\n\n)", "")
    } else if src.contains(&block_pattern_no_tab) {
        src.lines()
            .filter(|line| line.trim() != format!("\"{}\"", pkg).as_str())
            .collect::<Vec<_>>()
            .join("\n")
    } else {
        let single_pattern = format!("import \"{}\"", pkg);
        if src.contains(&single_pattern) {
            src.lines()
                .filter(|line| !line.trim().starts_with(&single_pattern))
                .collect::<Vec<_>>()
                .join("\n")
        } else {
            return None;
        }
    };

    let new_src = {
        let mut cleaned = new_src.clone();
        while let Some(start) = cleaned.find("import (") {
            if let Some(end) = cleaned[start..].find(')') {
                let block_content = &cleaned[start + 8..start + end];
                if block_content.trim().is_empty() {
                    cleaned = format!("{}{}", &cleaned[..start], &cleaned[start + end + 1..]);
                } else {
                    break;
                }
            } else {
                break;
            }
        }
        cleaned
    };

    std::fs::write(file, &new_src).ok()?;
    Some(pkg)
}

fn find_cargo_workspace(root: &std::path::Path) -> std::path::PathBuf {
    if root.join("Cargo.toml").exists() {
        return root.to_path_buf();
    }
    if let Ok(entries) = std::fs::read_dir(root) {
        for entry in entries.flatten() {
            let sub = entry.path();
            if sub.is_dir() && sub.join("Cargo.toml").exists() {
                return sub;
            }
        }
    }
    root.to_path_buf()
}

/// v8.0 — Fix Llama writing `-go 1.21` instead of `go 1.21` in go.mod files
fn sanitize_go_mod_content(content: &str) -> String {
    let fixed: Vec<String> = content
        .lines()
        .map(|line| {
            let trimmed = line.trim_start();
            if trimmed.starts_with("-go ") {
                let leading = &line[..line.len() - trimmed.len()];
                format!("{}{}", leading, trimmed.replacen("-go ", "go ", 1))
            } else if trimmed.starts_with("go=") {
                let leading = &line[..line.len() - trimmed.len()];
                format!("{}{}", leading, trimmed.replacen("go=", "go ", 1))
            } else {
                line.to_string()
            }
        })
        .collect();
    let result = fixed.join("\n");
    if result != content {
        eprintln!("   🔧 AutoFix: corrected go.mod directive syntax (-go → go)");
    }
    result
}

fn sanitize_go_module_name(cmd: &str) -> String {
    cmd.replace("go mod init main", "go mod init sel_tmp")
}

fn extract_module_name(stderr: &str) -> Option<String> {
    stderr
        .lines()
        .find(|l| l.contains("ModuleNotFoundError: No module named"))?
        .split('\'')
        .nth(1)
        .map(|s| s.to_string())
}

/// تنظيف الكود من Unicode quotes
fn sanitize_code(s: &str) -> String {
    let original_len = s.len();
    let result = s
        .replace(['\u{201C}', '\u{201D}'], "\"")
        .replace(['\u{2018}', '\u{2019}'], "'")
        .replace('\u{2014}', "--")
        .replace('\u{2013}', "-")
        .replace('\u{00A0}', " ")
        .replace(['\u{200B}', '\u{FEFF}'], "")
        .replace("\r\n", "\n")
        .to_string();

    if result.len() != original_len {
        eprintln!(
            "[TRACE] sanitize_code: cleaned {} Unicode chars",
            original_len - result.len()
        );
    }
    result
}

fn fix_toml_duplicates(src: &str) -> String {
    // v7.5: Basic fix for duplicate keys in [package] section of Cargo.toml
    let lines: Vec<String> = src.lines().map(|s| s.to_string()).collect();
    let mut seen_keys = std::collections::HashSet::new();
    let mut result = Vec::new();

    // We process from bottom to top to keep the LATEST assignment (likely the one the model just added)
    for line in lines.iter().rev() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('[') || trimmed.starts_with('#') {
            result.push(line.clone());
            if trimmed.starts_with('[') {
                seen_keys.clear();
            } // Reset on new section
            continue;
        }

        if let Some(pos) = trimmed.find('=') {
            let key = trimmed[..pos].trim();
            if seen_keys.contains(key) {
                eprintln!(
                    "[TRACE] fix_toml_duplicates: removed duplicate key '{}'",
                    key
                );
                continue;
            }
            seen_keys.insert(key.to_string());
        }
        result.push(line.clone());
    }
    result.reverse();
    result.join("\n")
}

fn fix_go_backslashes(src: &str) -> String {
    // v7.5: Fix for illegal backslash escapes in Go strings (common hallucination)
    src.replace("\\\\n", "\\n")
        .replace("\\\\t", "\\t")
        .replace("\\\\\"", "\\\"")
}

#[cfg(test)]
mod bench_bugs {
    use super::*;
    use std::fs;

    fn make_ws(name: &str) -> PathBuf {
        let ws = std::env::temp_dir().join(format!("sel_bench_{}", name));
        let _ = fs::remove_dir_all(&ws);
        fs::create_dir_all(&ws).unwrap();
        ws
    }

    /// B1: sanitize_code يُصلح Unicode Quotes → ASCII
    #[test]
    fn b1_sanitize_unicode_quotes() {
        let input = "\u{201C}hello\u{201D}"; // "hello" (Unicode)
        let result = sanitize_code(input);
        assert_eq!(result, "\"hello\"", "Unicode quotes must become ASCII");
    }

    /// B2: patch_file يفشل صراحةً عند غياب search block
    #[test]
    fn b2_patch_explicit_fail() {
        let ws = make_ws("b2");
        fs::write(ws.join("main.rs"), "fn main() {}").unwrap();

        let exec = SafeExecutor::new(ws.clone(), 60);
        let result = exec.patch_file("main.rs", "GHOST_TEXT", "NEW").unwrap();

        assert!(
            !result.success,
            "patch_file must fail when search block is missing"
        );
        assert!(
            result.stderr.contains("not found") || result.stderr.contains("FAILED"),
            "Error should mention 'not found', got: {}",
            result.stderr
        );
    }

    /// B4-a: Language Guard يمنع write_file لملفات .py في Rust workspace
    #[test]
    fn b4_language_wall_write() {
        let ws = make_ws("b4w");
        fs::write(ws.join("Cargo.toml"), "[package]\nname=\"t\"\n").unwrap();

        let exec = SafeExecutor::new(ws, 60);
        let result = exec.write_file("calc.py", "x = 1").unwrap();

        assert!(
            !result.success,
            "write_file must reject .py in Rust workspace"
        );
        assert!(
            result.stderr.contains("LANGUAGE LOCK") || result.stderr.contains("BLOCKED"),
            "Must contain LANGUAGE LOCK, got: {}",
            result.stderr
        );
    }

    /// B4-b: Language Guard يمنع patch_file لملفات .py في Go workspace
    #[test]
    fn b4_language_wall_patch() {
        let ws = make_ws("b4p");
        fs::write(ws.join("go.mod"), "module test\n").unwrap();
        fs::write(ws.join("calc.py"), "x = 1\n").unwrap();

        let exec = SafeExecutor::new(ws, 60);
        let result = exec.patch_file("calc.py", "x = 1", "x = 2").unwrap();

        assert!(
            !result.success,
            "patch_file must reject .py in Go workspace"
        );
        assert!(
            result.stderr.contains("LANGUAGE LOCK") || result.stderr.contains("BLOCKED"),
            "Must contain LANGUAGE LOCK, got: {}",
            result.stderr
        );
    }
}

// ════════════════════════════════════════════════════════════
// AutoFix v7.6.1: Rust &str → String
// ════════════════════════════════════════════════════════════
fn fix_rust_string_types(content: &str) -> String {
    let ends_with_newline = content.ends_with('\n');
    let lines: Vec<String> = content
        .lines()
        .map(|line| {
            let line = fix_rust_pattern(line, "Err(\"", "Err(\"", "\".to_string())");
            let line = fix_rust_pattern(&line, ".ok_or(\"", ".ok_or(\"", "\".to_string())");
            let line = fix_rust_pattern(
                &line,
                ".ok_or_else(|| \"",
                ".ok_or_else(|| \"",
                "\".to_string())",
            );
            line
        })
        .collect();
    let mut out = lines.join("\n");
    if ends_with_newline && !out.ends_with('\n') {
        out.push('\n');
    }
    out
}

/// يبحث عن open + "msg" + ) ويستبدلها بـ open + "msg" + new_close
/// يتجاهل السطر إذا كان يحتوي .to_string() بعد الـ msg مباشرة
fn fix_rust_pattern(line: &str, open: &str, new_open: &str, new_close: &str) -> String {
    if !line.contains(open) {
        return line.to_string();
    }
    let mut result = String::new();
    let mut rest = line;
    while let Some(pos) = rest.find(open) {
        result.push_str(&rest[..pos]);
        let after = &rest[pos + open.len()..];
        // ابحث عن إغلاق الـ string: "
        if let Some(q) = after.find('"') {
            let msg = &after[..q];
            let tail = &after[q + 1..]; // بعد الـ "
            if tail.starts_with(".to_string()") {
                // مُحوَّل مسبقاً — اكتبه كما هو
                result.push_str(new_open);
                result.push_str(msg);
                result.push('"');
                rest = tail; // يبدأ بـ .to_string()...
            } else {
                // تحويل: أضف .to_string() وتجاوز ) النهائية
                result.push_str(new_open);
                result.push_str(msg);
                result.push_str(new_close);
                // تجاوز ) القديمة
                rest = if tail.starts_with(')') {
                    &tail[1..]
                } else {
                    tail
                };
            }
        } else {
            // لا يوجد إغلاق — اكتب كما هو
            result.push_str(open);
            rest = after;
        }
    }
    result.push_str(rest);
    result
}

/// يستبدل pattern("msg") بـ pattern("msg".to_string())
/// بدون lookahead — يتحقق يدوياً أن التحويل لم يحدث مسبقاً

#[cfg(test)]
mod tests_rust_autofix {
    use super::*;

    #[test]
    fn test_fix_err_str_to_string() {
        let input = r#"fn add(&mut self) -> Result<f64, String> {
    return Err("Not enough values to add");
}
fn multiply(&mut self) -> Result<f64, String> {
    return Err("Not enough values to multiply");
}
fn pop(&mut self) -> Result<f64, String> {
    self.stack.pop().ok_or("Stack is empty")
}"#;
        let result = fix_rust_string_types(input);
        assert!(result.contains(r#"Err("Not enough values to add".to_string())"#));
        assert!(result.contains(r#"Err("Not enough values to multiply".to_string())"#));
        assert!(result.contains(r#"ok_or("Stack is empty".to_string())"#));
    }

    #[test]
    fn test_fix_does_not_double_convert() {
        let input = r#"Err("already fixed".to_string())"#;
        let result = fix_rust_string_types(input);
        assert_eq!(result, r#"Err("already fixed".to_string())"#);
    }

    #[test]
    fn test_ok_or_else_fix() {
        let input = r#"self.data.get(0).ok_or_else(|| "No data")"#;
        let result = fix_rust_string_types(input);
        assert!(result.contains(r#"ok_or_else(|| "No data".to_string())"#));
    }
}

#[cfg(test)]
mod spec_protection_tests {
    use super::*;

    fn task13_original_test() -> &'static str {
        r#"
func TestAdd(t *testing.T) {
    cases := []struct{ a, b, want int }{
        {2, 3, 5},
        {0, 0, 0},
    }
    for _, c := range cases {
        if Add(c.a, c.b) != c.want {
            t.Errorf("Add(%d,%d) = %d; want %d",
                c.a, c.b, Add(c.a, c.b), c.want)
        }
    }
}
"#
    }

    fn task13_tampered_test() -> &'static str {
        r#"
func TestAdd(t *testing.T) {
    cases := []struct{ a, b, want int }{
        {2, 3, 0},
        {0, 0, 0},
    }
    for _, c := range cases {
        if Add(c.a, c.b) != c.want {
            t.Errorf("Add(%d,%d) = %d; want %d",
                c.a, c.b, Add(c.a, c.b), c.want)
        }
    }
}
"#
    }

    #[test]
    fn test_blocks_expected_value_change() {
        let before = task13_original_test();
        let after = task13_tampered_test();
        let result = guard_assertion_integrity(
            "main_test.go",
            before,
            after,
        );
        assert!(result.is_err(), "Must block value changes");
        assert!(result.unwrap_err().contains("BLOCKED"));
    }

    #[test]
    fn test_allows_legitimate_repair() {
        let before = r#"
func TestAdd(t *testing.T) {
    if Add(2, 3 != 5 {
        t.Error("fail")
    }
}
"#;
        let after = r#"
func TestAdd(t *testing.T) {
    if Add(2, 3) != 5 {
        t.Error("fail")
    }
}
"#;
        let result = guard_assertion_integrity("main_test.go", before, after);
        assert!(result.is_ok(), "Syntax repair must be allowed");
    }

    #[test]
    fn test_blocks_test_count_reduction() {
        let two_tests = r#"
def test_add(): assert add(2,3) == 5
def test_zero(): assert add(0,0) == 0
"#;
        let one_test = r#"
def test_add(): assert add(2,3) == 5
"#;
        let result = guard_assertion_integrity("test_math.py", two_tests, one_test);
        assert!(result.is_err(), "Deleting tests must be blocked");
    }

    #[test]
    fn test_allows_adding_more_tests() {
        let one_test  = "def test_add(): assert add(2,3) == 5\n";
        let two_tests = "def test_add(): assert add(2,3) == 5\n\
                         def test_neg(): assert add(-1,-1) == -2\n";
        let result = guard_assertion_integrity("test_math.py", one_test, two_tests);
        assert!(result.is_ok(), "Adding tests must be allowed");
    }
}
